-- MySQL Script generated by MySQL Workbench
-- Thu Nov 25 22:22:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema notes_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema notes_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `notes_db` DEFAULT CHARACTER SET utf8 ;
USE `notes_db` ;

-- -----------------------------------------------------
-- Table `notes_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notes_db`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `notes_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notes_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `notes_db`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notes_db`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` VARCHAR(600) NOT NULL,
  `delete` TINYINT NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_posts_users_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_posts_users`
    FOREIGN KEY (`userId`)
    REFERENCES `notes_db`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `notes_db`.`post_cetegory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notes_db`.`post_cetegory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `postId` INT NOT NULL,
  `categoryId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_category_idx` (`postId` ASC) VISIBLE,
  INDEX `fk_category_post_idx` (`categoryId` ASC) VISIBLE,
  CONSTRAINT `fk_category_post`
    FOREIGN KEY (`categoryId`)
    REFERENCES `notes_db`.`categories` (`id`),
  CONSTRAINT `fk_post_category`
    FOREIGN KEY (`postId`)
    REFERENCES `notes_db`.`posts` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;